// <auto-generated />
using DracarysAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DracarysAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505134608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DracarysAPI.Models.Casa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Regiao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Casas");
                });

            modelBuilder.Entity("DracarysAPI.Models.Dragao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CasaId")
                        .HasColumnType("int");

                    b.Property<string>("Montador")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CasaId");

                    b.ToTable("Dragoes");
                });

            modelBuilder.Entity("DracarysAPI.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CasaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CasaId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("DracarysAPI.Models.Dragao", b =>
                {
                    b.HasOne("DracarysAPI.Models.Casa", "Casa")
                        .WithMany("Dragoes")
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("DracarysAPI.Models.Personagem", b =>
                {
                    b.HasOne("DracarysAPI.Models.Casa", "Casa")
                        .WithMany("Characters")
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("DracarysAPI.Models.Casa", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Dragoes");
                });
#pragma warning restore 612, 618
        }
    }
}
